apiVersion: cluster.etcd.io/v1beta1
kind: EtcdCluster
metadata:
  labels:
    app.kubernetes.io/name: etcdcluster
    app.kubernetes.io/instance: etcdcluster-sample
    app.kubernetes.io/part-of: etcd-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: etcd-operator
  name: etcdcluster-sample
spec:
  ports:
    - name: tcp
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    matchLabels:
      app: etcd
  serviceName: "my-etcd"
  replicas: 1
  template:
    labels:
      app: etcd
    spec:
      containers:
      - name: etcd
        image: nginx:latest
#        image: joinlulu/etcd-operator:v3.5.0
#        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: web
#        lifecycle:
#          preStop:
#            exec:
#              command: ["/bin/bash", "-ec", "/opt/PRESTOP"]
