apiVersion: cluster.etcd.io/v1beta1
kind: EtcdBackup
metadata:
  labels:
    app.kubernetes.io/name: etcdbackup
    app.kubernetes.io/instance: etcdbackup-sample
    app.kubernetes.io/part-of: etcd-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: etcd-operator
  name: etcdbackup-sample
spec:
  endpoints: "etcdcluster-sample-etcd-0.my-etcd.default.svc:2379"
  cos:
    bucket: "etcd-1308765018"
    filename: "etcd-snapshot.db"
    path: "/"
    region: "ap-beijing"
    secretId: "AKIDrXAYotqJrGWaYJxdO6nQrnkY7QYUFWkM"
    secretKey: "hP0a5vpttNrAHSYUE5qOl7VwNhqzxmU9"
  job:
#    concurrencyPolicy: Forbid
    schedule: "*/1 * * * *"
    jobTemplate:
      spec:
        template:
          spec:
            containers:
              - name: hello
                image: joinlulu/etcd-backup:latest
                imagePullPolicy: Always
            restartPolicy: OnFailure

