apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web12
spec:
  serviceName: "nginx1"
  replicas: 5
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
